const myDate = new Date();
// myDate.setFullYear("2024-04-14");
console.log(myDate);
console.log(myDate.toString());
console.log(myDate.toDateString());
console.log(myDate.toLocaleString());
console.log(myDate.toUTCString());
console.log(myDate.getMilliseconds());
console.log(Math.floor(Date.now()/1000));
console.log(myDate.getMonth());
console.log(myDate.getUTCDate());
console.log(myDate.getUTCMinutes());
console.log(myDate.getHours());
console.log(myDate.setFullYear(2024));
console.log(myDate.getFullYear());